services:
  mysql:
    image: mysql:8.0.23
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: shop

  mariadb:
    image: mariadb:10.5.8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: shop

  postgresql:
    image: postgres:13.1
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shop
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

volumes:
  mysql-data:
    driver: local
  mariadb-data:
    driver: local
  postgresql-data:
    driver: local
